//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace TrucoNetBackend.truconetDomain {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="truconetDomainSoap", Namespace="http://truconet/")]
    public partial class truconetDomain : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearPartidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaPartidoEnCursoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaPartidoRangosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaPartidoJugadoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaRankingOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaDenunciaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public truconetDomain() {
            this.Url = global::TrucoNetBackend.Properties.Settings.Default.TrucoNetBackend_truconetDomain_truconetDomain;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearPartidoCompletedEventHandler crearPartidoCompleted;
        
        /// <remarks/>
        public event consultaUsuarioCompletedEventHandler consultaUsuarioCompleted;
        
        /// <remarks/>
        public event consultaPartidoEnCursoCompletedEventHandler consultaPartidoEnCursoCompleted;
        
        /// <remarks/>
        public event consultaPartidoRangosCompletedEventHandler consultaPartidoRangosCompleted;
        
        /// <remarks/>
        public event consultaPartidoJugadoresCompletedEventHandler consultaPartidoJugadoresCompleted;
        
        /// <remarks/>
        public event consultaRankingCompletedEventHandler consultaRankingCompleted;
        
        /// <remarks/>
        public event consultaDenunciaCompletedEventHandler consultaDenunciaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/crearPartido", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string crearPartido() {
            object[] results = this.Invoke("crearPartido", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void crearPartidoAsync() {
            this.crearPartidoAsync(null);
        }
        
        /// <remarks/>
        public void crearPartidoAsync(object userState) {
            if ((this.crearPartidoOperationCompleted == null)) {
                this.crearPartidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearPartidoOperationCompleted);
            }
            this.InvokeAsync("crearPartido", new object[0], this.crearPartidoOperationCompleted, userState);
        }
        
        private void OncrearPartidoOperationCompleted(object arg) {
            if ((this.crearPartidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearPartidoCompleted(this, new crearPartidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/consultaUsuario", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario[] consultaUsuario() {
            object[] results = this.Invoke("consultaUsuario", new object[0]);
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync() {
            this.consultaUsuarioAsync(null);
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(object userState) {
            if ((this.consultaUsuarioOperationCompleted == null)) {
                this.consultaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaUsuarioOperationCompleted);
            }
            this.InvokeAsync("consultaUsuario", new object[0], this.consultaUsuarioOperationCompleted, userState);
        }
        
        private void OnconsultaUsuarioOperationCompleted(object arg) {
            if ((this.consultaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaUsuarioCompleted(this, new consultaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/consultaPartidoEnCurso", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Partido[] consultaPartidoEnCurso(bool enCurso) {
            object[] results = this.Invoke("consultaPartidoEnCurso", new object[] {
                        enCurso});
            return ((Partido[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaPartidoEnCursoAsync(bool enCurso) {
            this.consultaPartidoEnCursoAsync(enCurso, null);
        }
        
        /// <remarks/>
        public void consultaPartidoEnCursoAsync(bool enCurso, object userState) {
            if ((this.consultaPartidoEnCursoOperationCompleted == null)) {
                this.consultaPartidoEnCursoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaPartidoEnCursoOperationCompleted);
            }
            this.InvokeAsync("consultaPartidoEnCurso", new object[] {
                        enCurso}, this.consultaPartidoEnCursoOperationCompleted, userState);
        }
        
        private void OnconsultaPartidoEnCursoOperationCompleted(object arg) {
            if ((this.consultaPartidoEnCursoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaPartidoEnCursoCompleted(this, new consultaPartidoEnCursoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/consultaPartidoRangos", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Partido[] consultaPartidoRangos(System.DateTime fechaIni, System.DateTime fechaFin) {
            object[] results = this.Invoke("consultaPartidoRangos", new object[] {
                        fechaIni,
                        fechaFin});
            return ((Partido[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaPartidoRangosAsync(System.DateTime fechaIni, System.DateTime fechaFin) {
            this.consultaPartidoRangosAsync(fechaIni, fechaFin, null);
        }
        
        /// <remarks/>
        public void consultaPartidoRangosAsync(System.DateTime fechaIni, System.DateTime fechaFin, object userState) {
            if ((this.consultaPartidoRangosOperationCompleted == null)) {
                this.consultaPartidoRangosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaPartidoRangosOperationCompleted);
            }
            this.InvokeAsync("consultaPartidoRangos", new object[] {
                        fechaIni,
                        fechaFin}, this.consultaPartidoRangosOperationCompleted, userState);
        }
        
        private void OnconsultaPartidoRangosOperationCompleted(object arg) {
            if ((this.consultaPartidoRangosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaPartidoRangosCompleted(this, new consultaPartidoRangosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/consultaPartidoJugadores", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Partido[] consultaPartidoJugadores(Jugador[] listaJugadores) {
            object[] results = this.Invoke("consultaPartidoJugadores", new object[] {
                        listaJugadores});
            return ((Partido[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaPartidoJugadoresAsync(Jugador[] listaJugadores) {
            this.consultaPartidoJugadoresAsync(listaJugadores, null);
        }
        
        /// <remarks/>
        public void consultaPartidoJugadoresAsync(Jugador[] listaJugadores, object userState) {
            if ((this.consultaPartidoJugadoresOperationCompleted == null)) {
                this.consultaPartidoJugadoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaPartidoJugadoresOperationCompleted);
            }
            this.InvokeAsync("consultaPartidoJugadores", new object[] {
                        listaJugadores}, this.consultaPartidoJugadoresOperationCompleted, userState);
        }
        
        private void OnconsultaPartidoJugadoresOperationCompleted(object arg) {
            if ((this.consultaPartidoJugadoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaPartidoJugadoresCompleted(this, new consultaPartidoJugadoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/consultaRanking", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ranking[] consultaRanking() {
            object[] results = this.Invoke("consultaRanking", new object[0]);
            return ((Ranking[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaRankingAsync() {
            this.consultaRankingAsync(null);
        }
        
        /// <remarks/>
        public void consultaRankingAsync(object userState) {
            if ((this.consultaRankingOperationCompleted == null)) {
                this.consultaRankingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaRankingOperationCompleted);
            }
            this.InvokeAsync("consultaRanking", new object[0], this.consultaRankingOperationCompleted, userState);
        }
        
        private void OnconsultaRankingOperationCompleted(object arg) {
            if ((this.consultaRankingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaRankingCompleted(this, new consultaRankingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/consultaDenuncia", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Denuncia[] consultaDenuncia() {
            object[] results = this.Invoke("consultaDenuncia", new object[0]);
            return ((Denuncia[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaDenunciaAsync() {
            this.consultaDenunciaAsync(null);
        }
        
        /// <remarks/>
        public void consultaDenunciaAsync(object userState) {
            if ((this.consultaDenunciaOperationCompleted == null)) {
                this.consultaDenunciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaDenunciaOperationCompleted);
            }
            this.InvokeAsync("consultaDenuncia", new object[0], this.consultaDenunciaOperationCompleted, userState);
        }
        
        private void OnconsultaDenunciaOperationCompleted(object arg) {
            if ((this.consultaDenunciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaDenunciaCompleted(this, new consultaDenunciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Usuario {
        
        private int idField;
        
        private string eMailField;
        
        private string telefonoField;
        
        private string apellidoField;
        
        private string nombreField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Denuncia {
        
        private string desDenunciaField;
        
        private int codDenunciaField;
        
        /// <remarks/>
        public string DesDenuncia {
            get {
                return this.desDenunciaField;
            }
            set {
                this.desDenunciaField = value;
            }
        }
        
        /// <remarks/>
        public int CodDenuncia {
            get {
                return this.codDenunciaField;
            }
            set {
                this.codDenunciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Ranking {
        
        private string puntajeField;
        
        private Jugador jugField;
        
        private int posicionField;
        
        /// <remarks/>
        public string Puntaje {
            get {
                return this.puntajeField;
            }
            set {
                this.puntajeField = value;
            }
        }
        
        /// <remarks/>
        public Jugador Jug {
            get {
                return this.jugField;
            }
            set {
                this.jugField = value;
            }
        }
        
        /// <remarks/>
        public int Posicion {
            get {
                return this.posicionField;
            }
            set {
                this.posicionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Jugador {
        
        private cartasMano manoField;
        
        private bool esManoField;
        
        /// <remarks/>
        public cartasMano Mano {
            get {
                return this.manoField;
            }
            set {
                this.manoField = value;
            }
        }
        
        /// <remarks/>
        public bool EsMano {
            get {
                return this.esManoField;
            }
            set {
                this.esManoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class cartasMano {
        
        private int puntosField;
        
        private int jugadaField;
        
        private Carta[] cartasField;
        
        /// <remarks/>
        public int Puntos {
            get {
                return this.puntosField;
            }
            set {
                this.puntosField = value;
            }
        }
        
        /// <remarks/>
        public int Jugada {
            get {
                return this.jugadaField;
            }
            set {
                this.jugadaField = value;
            }
        }
        
        /// <remarks/>
        public Carta[] Cartas {
            get {
                return this.cartasField;
            }
            set {
                this.cartasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Carta {
        
        private int codField;
        
        private int numeroField;
        
        private int puntajeField;
        
        private int paloField;
        
        private int categoriaField;
        
        private Jugador jugadorField;
        
        /// <remarks/>
        public int Cod {
            get {
                return this.codField;
            }
            set {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public int Puntaje {
            get {
                return this.puntajeField;
            }
            set {
                this.puntajeField = value;
            }
        }
        
        /// <remarks/>
        public int Palo {
            get {
                return this.paloField;
            }
            set {
                this.paloField = value;
            }
        }
        
        /// <remarks/>
        public int Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        public Jugador Jugador {
            get {
                return this.jugadorField;
            }
            set {
                this.jugadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Partido {
        
        private int idField;
        
        private Jugador[] ganadoresField;
        
        private System.DateTime fechaFinField;
        
        private System.DateTime fechaInicioField;
        
        private Jugador[] participantesField;
        
        private int identificadorField;
        
        private Carta muestraField;
        
        private string descripcionField;
        
        private Carta[] masoJuegoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Jugador[] Ganadores {
            get {
                return this.ganadoresField;
            }
            set {
                this.ganadoresField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        public Jugador[] Participantes {
            get {
                return this.participantesField;
            }
            set {
                this.participantesField = value;
            }
        }
        
        /// <remarks/>
        public int Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public Carta Muestra {
            get {
                return this.muestraField;
            }
            set {
                this.muestraField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public Carta[] MasoJuego {
            get {
                return this.masoJuegoField;
            }
            set {
                this.masoJuegoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void crearPartidoCompletedEventHandler(object sender, crearPartidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearPartidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearPartidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void consultaUsuarioCompletedEventHandler(object sender, consultaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void consultaPartidoEnCursoCompletedEventHandler(object sender, consultaPartidoEnCursoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaPartidoEnCursoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaPartidoEnCursoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Partido[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Partido[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void consultaPartidoRangosCompletedEventHandler(object sender, consultaPartidoRangosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaPartidoRangosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaPartidoRangosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Partido[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Partido[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void consultaPartidoJugadoresCompletedEventHandler(object sender, consultaPartidoJugadoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaPartidoJugadoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaPartidoJugadoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Partido[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Partido[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void consultaRankingCompletedEventHandler(object sender, consultaRankingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaRankingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaRankingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ranking[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ranking[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void consultaDenunciaCompletedEventHandler(object sender, consultaDenunciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaDenunciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaDenunciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Denuncia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Denuncia[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591