//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace truconetWeb.truconetFachadaProxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="truconetFachadaSoap", Namespace="http://truconet/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Usuario))]
    public partial class truconetFachada : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerJugadoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearPartidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getjugadorPartidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPartidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPartidosPendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback borrarParticipanteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public truconetFachada() {
            this.Url = global::truconetWeb.Properties.Settings.Default.truconetWeb_truconetFachadaProxy_truconetFachada;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerJugadoresCompletedEventHandler obtenerJugadoresCompleted;
        
        /// <remarks/>
        public event crearPartidoCompletedEventHandler crearPartidoCompleted;
        
        /// <remarks/>
        public event getjugadorPartidoCompletedEventHandler getjugadorPartidoCompleted;
        
        /// <remarks/>
        public event getPartidoCompletedEventHandler getPartidoCompleted;
        
        /// <remarks/>
        public event getPartidosPendientesCompletedEventHandler getPartidosPendientesCompleted;
        
        /// <remarks/>
        public event borrarParticipanteCompletedEventHandler borrarParticipanteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/obtenerJugadores", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Jugador[] obtenerJugadores() {
            object[] results = this.Invoke("obtenerJugadores", new object[0]);
            return ((Jugador[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerJugadoresAsync() {
            this.obtenerJugadoresAsync(null);
        }
        
        /// <remarks/>
        public void obtenerJugadoresAsync(object userState) {
            if ((this.obtenerJugadoresOperationCompleted == null)) {
                this.obtenerJugadoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerJugadoresOperationCompleted);
            }
            this.InvokeAsync("obtenerJugadores", new object[0], this.obtenerJugadoresOperationCompleted, userState);
        }
        
        private void OnobtenerJugadoresOperationCompleted(object arg) {
            if ((this.obtenerJugadoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerJugadoresCompleted(this, new obtenerJugadoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/crearPartido", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int crearPartido() {
            object[] results = this.Invoke("crearPartido", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void crearPartidoAsync() {
            this.crearPartidoAsync(null);
        }
        
        /// <remarks/>
        public void crearPartidoAsync(object userState) {
            if ((this.crearPartidoOperationCompleted == null)) {
                this.crearPartidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearPartidoOperationCompleted);
            }
            this.InvokeAsync("crearPartido", new object[0], this.crearPartidoOperationCompleted, userState);
        }
        
        private void OncrearPartidoOperationCompleted(object arg) {
            if ((this.crearPartidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearPartidoCompleted(this, new crearPartidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/getjugadorPartido", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Jugador[] getjugadorPartido(int idPartido) {
            object[] results = this.Invoke("getjugadorPartido", new object[] {
                        idPartido});
            return ((Jugador[])(results[0]));
        }
        
        /// <remarks/>
        public void getjugadorPartidoAsync(int idPartido) {
            this.getjugadorPartidoAsync(idPartido, null);
        }
        
        /// <remarks/>
        public void getjugadorPartidoAsync(int idPartido, object userState) {
            if ((this.getjugadorPartidoOperationCompleted == null)) {
                this.getjugadorPartidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetjugadorPartidoOperationCompleted);
            }
            this.InvokeAsync("getjugadorPartido", new object[] {
                        idPartido}, this.getjugadorPartidoOperationCompleted, userState);
        }
        
        private void OngetjugadorPartidoOperationCompleted(object arg) {
            if ((this.getjugadorPartidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getjugadorPartidoCompleted(this, new getjugadorPartidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/getPartido", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Partido getPartido(int idPartido) {
            object[] results = this.Invoke("getPartido", new object[] {
                        idPartido});
            return ((Partido)(results[0]));
        }
        
        /// <remarks/>
        public void getPartidoAsync(int idPartido) {
            this.getPartidoAsync(idPartido, null);
        }
        
        /// <remarks/>
        public void getPartidoAsync(int idPartido, object userState) {
            if ((this.getPartidoOperationCompleted == null)) {
                this.getPartidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPartidoOperationCompleted);
            }
            this.InvokeAsync("getPartido", new object[] {
                        idPartido}, this.getPartidoOperationCompleted, userState);
        }
        
        private void OngetPartidoOperationCompleted(object arg) {
            if ((this.getPartidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPartidoCompleted(this, new getPartidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/getPartidosPendientes", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Partido[] getPartidosPendientes() {
            object[] results = this.Invoke("getPartidosPendientes", new object[0]);
            return ((Partido[])(results[0]));
        }
        
        /// <remarks/>
        public void getPartidosPendientesAsync() {
            this.getPartidosPendientesAsync(null);
        }
        
        /// <remarks/>
        public void getPartidosPendientesAsync(object userState) {
            if ((this.getPartidosPendientesOperationCompleted == null)) {
                this.getPartidosPendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPartidosPendientesOperationCompleted);
            }
            this.InvokeAsync("getPartidosPendientes", new object[0], this.getPartidosPendientesOperationCompleted, userState);
        }
        
        private void OngetPartidosPendientesOperationCompleted(object arg) {
            if ((this.getPartidosPendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPartidosPendientesCompleted(this, new getPartidosPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://truconet/borrarParticipante", RequestNamespace="http://truconet/", ResponseNamespace="http://truconet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool borrarParticipante(int idJugador, int idPartido) {
            object[] results = this.Invoke("borrarParticipante", new object[] {
                        idJugador,
                        idPartido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void borrarParticipanteAsync(int idJugador, int idPartido) {
            this.borrarParticipanteAsync(idJugador, idPartido, null);
        }
        
        /// <remarks/>
        public void borrarParticipanteAsync(int idJugador, int idPartido, object userState) {
            if ((this.borrarParticipanteOperationCompleted == null)) {
                this.borrarParticipanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnborrarParticipanteOperationCompleted);
            }
            this.InvokeAsync("borrarParticipante", new object[] {
                        idJugador,
                        idPartido}, this.borrarParticipanteOperationCompleted, userState);
        }
        
        private void OnborrarParticipanteOperationCompleted(object arg) {
            if ((this.borrarParticipanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.borrarParticipanteCompleted(this, new borrarParticipanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Jugador : Usuario {
        
        private cartasMano manoField;
        
        private bool esManoField;
        
        /// <remarks/>
        public cartasMano Mano {
            get {
                return this.manoField;
            }
            set {
                this.manoField = value;
            }
        }
        
        /// <remarks/>
        public bool EsMano {
            get {
                return this.esManoField;
            }
            set {
                this.esManoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class cartasMano {
        
        private int puntosField;
        
        private int jugadaField;
        
        private Carta[] cartasField;
        
        private int idPartidoField;
        
        /// <remarks/>
        public int Puntos {
            get {
                return this.puntosField;
            }
            set {
                this.puntosField = value;
            }
        }
        
        /// <remarks/>
        public int Jugada {
            get {
                return this.jugadaField;
            }
            set {
                this.jugadaField = value;
            }
        }
        
        /// <remarks/>
        public Carta[] Cartas {
            get {
                return this.cartasField;
            }
            set {
                this.cartasField = value;
            }
        }
        
        /// <remarks/>
        public int IdPartido {
            get {
                return this.idPartidoField;
            }
            set {
                this.idPartidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Carta {
        
        private int codField;
        
        private int numeroField;
        
        private int puntajeField;
        
        private int paloField;
        
        private int categoriaField;
        
        private Jugador jugadorField;
        
        /// <remarks/>
        public int Cod {
            get {
                return this.codField;
            }
            set {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public int Puntaje {
            get {
                return this.puntajeField;
            }
            set {
                this.puntajeField = value;
            }
        }
        
        /// <remarks/>
        public int Palo {
            get {
                return this.paloField;
            }
            set {
                this.paloField = value;
            }
        }
        
        /// <remarks/>
        public int Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        public Jugador Jugador {
            get {
                return this.jugadorField;
            }
            set {
                this.jugadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Partido {
        
        private int idField;
        
        private Jugador[] ganadoresField;
        
        private System.DateTime fechaFinField;
        
        private System.DateTime fechaInicioField;
        
        private Jugador[] participantesField;
        
        private int identificadorField;
        
        private Carta muestraField;
        
        private string descripcionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Jugador[] Ganadores {
            get {
                return this.ganadoresField;
            }
            set {
                this.ganadoresField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        public Jugador[] Participantes {
            get {
                return this.participantesField;
            }
            set {
                this.participantesField = value;
            }
        }
        
        /// <remarks/>
        public int Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public Carta Muestra {
            get {
                return this.muestraField;
            }
            set {
                this.muestraField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Jugador))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://truconet/")]
    public partial class Usuario {
        
        private int idField;
        
        private string eMailField;
        
        private string telefonoField;
        
        private string apellidoField;
        
        private string nombreField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void obtenerJugadoresCompletedEventHandler(object sender, obtenerJugadoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerJugadoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerJugadoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Jugador[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Jugador[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void crearPartidoCompletedEventHandler(object sender, crearPartidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearPartidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearPartidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getjugadorPartidoCompletedEventHandler(object sender, getjugadorPartidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getjugadorPartidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getjugadorPartidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Jugador[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Jugador[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getPartidoCompletedEventHandler(object sender, getPartidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPartidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPartidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Partido Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Partido)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getPartidosPendientesCompletedEventHandler(object sender, getPartidosPendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPartidosPendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPartidosPendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Partido[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Partido[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void borrarParticipanteCompletedEventHandler(object sender, borrarParticipanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class borrarParticipanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal borrarParticipanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591